---
- name: Setup a Workshop for RHEL Image Mode
  hosts: localhost
  become: yes
  gather_facts: yes
  connection: local
  vars:
    HOSTNAME: "build"
    DOMAINNAME: "example.com"
    USERNAME: "lab-user"
    USERPASSWORD: "redhat"
    SERVERNAME: "server"
    REGISTRYNAME: "registry"
    REGISTRYDIR: /root/registry

  tasks:

  - name: Set the hostname
    ansible.builtin.hostname:
      name: "{{ HOSTNAME }}.{{ DOMAINNAME }}"

  - name: Add {{ HOSTNAME }} {{ HOSTNAME }}.{{ DOMAINNAME }} to /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1'
      line: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 {{ HOSTNAME }} {{ HOSTNAME }}.{{ DOMAINNAME }}"
      owner: root
      group: root
      mode: 0644

  - name: Add dns entries to /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{HOST_ENTRIES}}"  
    vars:
      HOST_ENTRIES:
      - "192.168.122.101 {{ SERVERNAME }} {{ SERVERNAME }}.{{ DOMAINNAME }}"
      - "192.168.122.1 {{ REGISTRYNAME }} {{ REGISTRYNAME }}.{{ DOMAINNAME }}"

  - name: Make sure {{USERNAME}} exists
    ansible.builtin.user:
      name: "{{USERNAME}}"
      groups: wheel

  - name: Set the users password
    ansible.builtin.shell:
      cmd: usermod -p $(openssl passwd -1 {{USERPASSWORD}}) {{USERNAME}}
     
  - name: Install packages
    ansible.builtin.yum:
      name: "{{ rpm_packages }}"
    vars:
      rpm_packages:
      - "@Virtualization Host"
      - virt-manager
      - virt-install
      - cockpit-machines
      - httpd
      - podman

  - name: Enable Linger
    ansible.builtin.shell:
      cmd: loginctl enable-linger {{USERNAME}}

  - name: Add user to libvirtd
    ansible.builtin.shell:
      cmd: usermod -aG libvirt {{USERNAME}}

  - name: Enable and start libvirt
    ansible.builtin.systemd_service:
      name: libvirtd
      enabled: true
      state: started

  - name: Enable and start cockpit
    ansible.builtin.systemd_service:
      name: cockpit.socket
      enabled: true
      state: started

  - name: Enable and start dnsmasq
    ansible.builtin.systemd_service:
      name: dnsmasq
      enabled: true
      state: started

  - name: Enable and start httpd
    ansible.builtin.systemd_service:
      name: httpd
      enabled: true
      state: started

  - name: Set necessary permissions for newgidmap
    ansible.builtin.file:
      path: /usr/bin/newgidmap
      mode: '4755'

  - name: Set necessary permissions for newuidmap
    ansible.builtin.file:
      path: /usr/bin/newuidmap
      mode: '4755'

  - name: Create a mount point for the ISO
    ansible.builtin.file:
      path: /var/www/html/RHEL
      state: directory

  #- name: Mount the ISO 
  #  ansible.posix.mount:
  #    path: /var/www/html/RHEL
  #    src: /mnt/iso/rhel-9.4-x86_64-dvd.iso
  #    fstype: iso9660
  #    opts: loop
  #    state: present
# Above doesn't work, so do this via a command

  - name: Mount DVD ##### This isn't idempotent #####
    ansible.builtin.command: mount -o loop /mnt/iso/rhel-9.4-x86_64-dvd.iso /var/www/html/RHEL

  - name: Create kickstart file
    ansible.builtin.copy:
      src: files/imagemode.cfg
      dest: /var/www/html/imagemode.cfg

  - name: Create the root CA for example.com
    ansible.builtin.copy:
      src: files/ca.example.com.crt
      dest: /var/www/html/ca.example.com.crt

  - name: Create the data directory for the registry container
    ansible.builtin.file:
      path: "{{ REGISTRYDIR }}/data"
      state: directory

  - name: Create the certs directory for the registry container
    ansible.builtin.file:
      path: "{{ REGISTRYDIR }}/certs"
      state: directory

  - name: Install the registry crt
    ansible.builtin.copy:
      src: files/wildcard.example.com.crt
      dest: "{{ REGISTRYDIR }}/certs/wildcard.example.com.crt"

  - name: Install the registry key
    ansible.builtin.copy:
      src: files/wildcard.example.com.key
      dest: "{{ REGISTRYDIR }}/certs/wildcard.example.com.key"

  - name: Create a container
    containers.podman.podman_container:
      name: registry
      privileged: true
      publish: 443:5000
      volume:
      - "{{ REGISTRYDIR }}/certs:/certs"
      - "{{ REGISTRYDIR }}/data:/var/lib/registry:Z"
      state: started
      image: registry:latest
      env:
        REGISTRY_HTTP_TLS_CERTIFICATE: certs/wildcard.example.com.crt
        REGISTRY_HTTP_TLS_KEY: certs/wildcard.example.com.key

##### TO DO #####
# Create KVM?  Maybe just create one in cockpit and add inst.ks=http://192.168.122.1/imagemode.cfg
# Add some images to the registry to use
# Add a Containerfile
# Add example.com rpm to webserver