---
- name: Setup a Workshop for RHEL Image Mode
  hosts: localhost
  become: yes
  gather_facts: yes
  connection: local
  vars:
    HOSTNAME: "build"
    DOMAINNAME: "example.com"
    USERNAME: "lab-user"
    USERPASSWORD: "redhat"

  tasks:

  - name: Set the hostname
    ansible.builtin.hostname:
      name: "{{ HOSTNAME }}.{{ DOMAINNAME }}"

  - name: Add the hostname to /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1'
      line: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 {{ HOSTNAME }} {{ HOSTNAME }}.{{ DOMAINNAME }}"
      owner: root
      group: root
      mode: 0644

  -name: Set the users password
   ansible.builtin.shell:
     cmd: usermod -p $(openssl passwd -1 {{USERPASSWORD}}) {{USERNAME}}
     
  - name: Install packages
    ansible.builtin.yum:
      name: "{{ rpm_packages }}"
    vars:
      rpm_packages:
      - "@Virtualization Host"
      - virt-manager
      - virt-install
      - cockpit-machines

  -name: Enable Linger
   ansible.builtin.shell:
     cmd: loginctl enable-linger {{USERNAME}}

  - name: Add user to libvirtd
    ansible.builtin.shell:
      cmd: usermod -aG libvirt {{USERNAME}}

  - name: Enable and start services
    ansible.builtin.systemd_service:
      name: "{{start_services}}"
      enabled: true
      state: started
    vars:
      start_services:
      - cockpit.socket
      - libvirtd

  - name: Set necessary permissions for podman
    ansible.builtin.file:
      path: "{{file_permissions}}"
      mode: '4755'
    vars:
      file_permissions:
      - /usr/bin/newgidmap
      - /usr/bin/newuidmap