name: Build and Push RHEL 9 SOE Image

on:
  push:
    branches:
      - main
      
jobs:

  build:
  
    #runs-on: ubuntu-latest
    runs-on: runner

    steps:

    - name: Add example.com to /etc/hosts
      run: echo "192.168.122.1 server.example.com" | sudo tee -a /etc/hosts

    - name: Make directory structure
      run: sudo mkdir -p /usr/local/share/ca-certificates/extra

    - name: uname
      run: uname -a

    - name: Show info
      run: echo "The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."

    - name: Ping server
      run: ping -c 2 server.example.com

    - name: Get CA and install it
      #run: curl http://server.example.com/ca.example.com.crt -o /etc/ssl/certs/ca.example.com.crt && update-ca-certificates
      run: curl http://server.example.com/ca.example.com.crt | sudo tee -a /usr/local/share/ca-certificates/extra/ca.example.com.crt && sudo update-ca-trust # sudo update-ca-certificates

    - name: Clone repository
      uses: actions/checkout@v4 # https://github.com/actions/checkout
      with:
        repository: 'server.example.com:3000/lab-user/rhel9-soe'

    - name: Log in to registry.redhat.io
      uses: docker/login-action@v3
      with:
        registry: registry.redhat.io
        username: rhn-support-cshabazi
        password: D3vild0g!

    - name: Build and push container
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./Containerfile
        push: true
        tags: registry.example.com/rhel9/rhel9_soe:latest
