FROM registry.example.com/rhel9/rhel-bootc:latest
COPY local.repo /etc/yum.repos.d/local.repo
RUN dnf install -y java-17-openjdk.x86_64 mariadb-server
RUN systemctl enable mariadb --now
RUN ln -s /usr/lib/jvm/jre-17-openjdk-17.0.10.0.7-2.el9.x86_64/bin/java /usr/bin/java
COPY *.jar /opt/spring-petclinic.jar