FROM registry.example.com/rhel9/rhel-bootc:latest
COPY local.repo /etc/yum.repos.d/local.repo
RUN dnf install -y java-11-openjdk.x86_64 mariadb-server
RUN systemctl enable mariadb
RUN ln -s /usr/lib/jvm/java-11-openjdk-11.0.22.0.7-2.el9.x86_64/bin/java /usr/bin/java
COPY *.jar /opt/spring-petclinic.jar
